[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = ../libraries
lib_deps =
    ArduinoJson
    MPU6050_tockn
    SCServo
    SimpleFOC

monitor_speed = 1000000